"""added relations

Revision ID: 112d8385b903
Revises: 871a03be39ec
Create Date: 2026-01-30 19:11:28.504698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '112d8385b903'
down_revision: Union[str, Sequence[str], None] = '871a03be39ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymenthistory',
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('invoice_id', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('next_billing_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("currency IN ('NGN', 'USD')", name='check_currency'),
    sa.CheckConstraint("status IN ('Active', 'Pending','Expired')", name='check_status'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.invoice_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['buildingproject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paymenthistory_id'), 'paymenthistory', ['id'], unique=False)
    op.create_index(op.f('ix_paymenthistory_invoice_id'), 'paymenthistory', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_paymenthistory_plan_id'), 'paymenthistory', ['plan_id'], unique=False)
    op.create_index(op.f('ix_paymenthistory_project_id'), 'paymenthistory', ['project_id'], unique=False)
    op.drop_index(op.f('ix_projectpayment_id'), table_name='projectpayment')
    op.drop_index(op.f('ix_projectpayment_milestone_id'), table_name='projectpayment')
    op.drop_index(op.f('ix_projectpayment_project_id'), table_name='projectpayment')
    op.drop_table('projectpayment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectpayment',
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('milestone_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'PAID', 'APPROVED', name='payment_status_emum'), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("currency::text = ANY (ARRAY['NGN'::character varying, 'USD'::character varying]::text[])", name=op.f('check_currency')),
    sa.ForeignKeyConstraint(['milestone_id'], ['projectmilestone.id'], name=op.f('projectpayment_milestone_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['buildingproject.id'], name=op.f('projectpayment_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('projectpayment_pkey'))
    )
    op.create_index(op.f('ix_projectpayment_project_id'), 'projectpayment', ['project_id'], unique=False)
    op.create_index(op.f('ix_projectpayment_milestone_id'), 'projectpayment', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_projectpayment_id'), 'projectpayment', ['id'], unique=False)
    op.drop_index(op.f('ix_paymenthistory_project_id'), table_name='paymenthistory')
    op.drop_index(op.f('ix_paymenthistory_plan_id'), table_name='paymenthistory')
    op.drop_index(op.f('ix_paymenthistory_invoice_id'), table_name='paymenthistory')
    op.drop_index(op.f('ix_paymenthistory_id'), table_name='paymenthistory')
    op.drop_table('paymenthistory')
    # ### end Alembic commands ###
