"""added relations

Revision ID: 1e184125edbf
Revises: 
Create Date: 2026-02-08 05:32:45.476720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e184125edbf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailverificationcodes',
    sa.Column('email', sa.String(length=500), nullable=False),
    sa.Column('otp_code', sa.String(length=4), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'otp_code', name='uq_email_otp')
    )
    op.create_index(op.f('ix_emailverificationcodes_email'), 'emailverificationcodes', ['email'], unique=False)
    op.create_index(op.f('ix_emailverificationcodes_id'), 'emailverificationcodes', ['id'], unique=False)
    op.create_index(op.f('ix_emailverificationcodes_otp_code'), 'emailverificationcodes', ['otp_code'], unique=False)
    op.create_table('permission',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_permission_id'), 'permission', ['id'], unique=False)
    op.create_table('plan',
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('slug', sa.String(length=225), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('plan_status', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('deactivate', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("currency IN ('NGN', 'USD')", name='check_currency'),
    sa.CheckConstraint("frequency IN ('Monthly', 'Yearly')", name='check_frequency'),
    sa.CheckConstraint("plan_status IN ('Free', 'Paid')", name='check_plan_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_id'), 'plan', ['id'], unique=False)
    op.create_table('role',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('user',
    sa.Column('first_name', sa.String(length=225), nullable=False),
    sa.Column('last_name', sa.String(length=225), nullable=False),
    sa.Column('email', sa.String(length=500), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='USER', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('SUPER_ADMIN', 'USER')", name='check_user_role_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('buildingproject',
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.Enum('RESIDENTIAL', 'COMMERCIAL', 'INFRASTRUCTURE', name='project_type_emum'), nullable=False),
    sa.Column('location_text', sa.String(length=500), nullable=True),
    sa.Column('location_map', sa.String(length=500), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('budget', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('budget_currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('preferred_inspection_days', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('subscription_end_date', sa.Date(), nullable=True),
    sa.Column('preferred_inspection_window', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("budget_currency IN ('NGN', 'USD')", name='check_budget_currency'),
    sa.CheckConstraint("payment_status IN ('Active', 'Pending','Expired')", name='check_payment_status'),
    sa.CheckConstraint("preferred_inspection_days <@ ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']::varchar[]", name='check_inspection_days'),
    sa.CheckConstraint("preferred_inspection_window IN ('Morning','Afternoon','Evening')", name='check_inspection_window'),
    sa.CheckConstraint("status IN ('Active', 'Pending','Draft','Completed')", name='check_status'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildingproject_id'), 'buildingproject', ['id'], unique=False)
    op.create_index(op.f('ix_buildingproject_owner_id'), 'buildingproject', ['owner_id'], unique=False)
    op.create_index(op.f('ix_buildingproject_plan_id'), 'buildingproject', ['plan_id'], unique=False)
    op.create_table('package',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('count', sa.Float(), nullable=True),
    sa.Column('tag', sa.String(length=225), nullable=True),
    sa.Column('is_unlimited', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_id'), 'package', ['id'], unique=False)
    op.create_index(op.f('ix_package_plan_id'), 'package', ['plan_id'], unique=False)
    op.create_table('rolepermission',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rolepermission_id'), 'rolepermission', ['id'], unique=False)
    op.create_index(op.f('ix_rolepermission_permission_id'), 'rolepermission', ['permission_id'], unique=False)
    op.create_index(op.f('ix_rolepermission_role_id'), 'rolepermission', ['role_id'], unique=False)
    op.create_table('invoice',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('invoice_id', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('billing_period_months', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("currency IN ('NGN', 'USD')", name='check_invoice_currency'),
    sa.CheckConstraint("status IN ('PENDING', 'PAID', 'OVERDUE', 'CANCELLED')", name='check_invoice_status'),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['buildingproject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invoice_id', 'id')
    )
    op.create_index(op.f('ix_invoice_id'), 'invoice', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_invoice_id'), 'invoice', ['invoice_id'], unique=True)
    op.create_index(op.f('ix_invoice_plan_id'), 'invoice', ['plan_id'], unique=False)
    op.create_index(op.f('ix_invoice_project_id'), 'invoice', ['project_id'], unique=False)
    op.create_table('planpackageusagecount',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('package_tag', sa.String(length=50), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['buildingproject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planpackageusagecount_id'), 'planpackageusagecount', ['id'], unique=False)
    op.create_index(op.f('ix_planpackageusagecount_project_id'), 'planpackageusagecount', ['project_id'], unique=False)
    op.create_table('projectmember',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['buildingproject.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projectmember_id'), 'projectmember', ['id'], unique=False)
    op.create_index(op.f('ix_projectmember_project_id'), 'projectmember', ['project_id'], unique=False)
    op.create_index(op.f('ix_projectmember_role_id'), 'projectmember', ['role_id'], unique=False)
    op.create_index(op.f('ix_projectmember_user_id'), 'projectmember', ['user_id'], unique=False)
    op.create_table('projectmilestone',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=225), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_deliverables', sa.Text(), nullable=True),
    sa.Column('payment_percentage', sa.Float(), nullable=True),
    sa.Column('payment_amount', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('sequential_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ONGOING', 'COMPLETED', 'APPROVED', name='milestone_status_enum'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("currency IN ('NGN', 'USD')", name='check_currency'),
    sa.ForeignKeyConstraint(['project_id'], ['buildingproject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projectmilestone_id'), 'projectmilestone', ['id'], unique=False)
    op.create_index(op.f('ix_projectmilestone_project_id'), 'projectmilestone', ['project_id'], unique=False)
    op.create_table('projectreport',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=225), nullable=False),
    sa.Column('report_type', sa.Enum('DAILY', 'WEEKLY', 'MILESTONE', 'INCIDENT', name='report_type_enum'), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['buildingproject.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projectreport_id'), 'projectreport', ['id'], unique=False)
    op.create_index(op.f('ix_projectreport_project_id'), 'projectreport', ['project_id'], unique=False)
    op.create_index(op.f('ix_projectreport_submitted_by'), 'projectreport', ['submitted_by'], unique=False)
    op.create_table('projectupload',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['buildingproject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projectupload_id'), 'projectupload', ['id'], unique=False)
    op.create_index(op.f('ix_projectupload_project_id'), 'projectupload', ['project_id'], unique=False)
    op.create_table('paymenthistory',
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('invoice_id', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('next_billing_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("currency IN ('NGN', 'USD')", name='check_currency'),
    sa.CheckConstraint("status IN ('Active', 'Pending','Expired')", name='check_status'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.invoice_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['buildingproject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paymenthistory_id'), 'paymenthistory', ['id'], unique=False)
    op.create_index(op.f('ix_paymenthistory_invoice_id'), 'paymenthistory', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_paymenthistory_plan_id'), 'paymenthistory', ['plan_id'], unique=False)
    op.create_index(op.f('ix_paymenthistory_project_id'), 'paymenthistory', ['project_id'], unique=False)
    op.create_table('reportupload',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['projectreport.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reportupload_id'), 'reportupload', ['id'], unique=False)
    op.create_index(op.f('ix_reportupload_report_id'), 'reportupload', ['report_id'], unique=False)
    op.create_table('transaction',
    sa.Column('invoice_id', sa.String(length=100), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('authorization_url', sa.String(length=200), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_reference', sa.String(length=400), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("currency IN ('NGN', 'USD')", name='check_transaction_currency'),
    sa.CheckConstraint("provider IN ('PAYSTACK','FLUTTERWAVE','STRIPE','PAYPAL','BANK_TRANSFER','CRYPTO')", name='check_transaction_provider'),
    sa.CheckConstraint("status IN ('SUCCESS', 'FAILED', 'REFUNDED','PENDING')", name='check_transaction_status'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.invoice_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['buildingproject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_reference', name='uq_provider_provider_reference')
    )
    op.create_index(op.f('ix_transaction_id'), 'transaction', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_invoice_id'), 'transaction', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_transaction_project_id'), 'transaction', ['project_id'], unique=False)
    op.create_index(op.f('ix_transaction_provider_reference'), 'transaction', ['provider_reference'], unique=False)
    op.create_index(op.f('ix_transaction_reference'), 'transaction', ['reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_reference'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_provider_reference'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_project_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_invoice_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_reportupload_report_id'), table_name='reportupload')
    op.drop_index(op.f('ix_reportupload_id'), table_name='reportupload')
    op.drop_table('reportupload')
    op.drop_index(op.f('ix_paymenthistory_project_id'), table_name='paymenthistory')
    op.drop_index(op.f('ix_paymenthistory_plan_id'), table_name='paymenthistory')
    op.drop_index(op.f('ix_paymenthistory_invoice_id'), table_name='paymenthistory')
    op.drop_index(op.f('ix_paymenthistory_id'), table_name='paymenthistory')
    op.drop_table('paymenthistory')
    op.drop_index(op.f('ix_projectupload_project_id'), table_name='projectupload')
    op.drop_index(op.f('ix_projectupload_id'), table_name='projectupload')
    op.drop_table('projectupload')
    op.drop_index(op.f('ix_projectreport_submitted_by'), table_name='projectreport')
    op.drop_index(op.f('ix_projectreport_project_id'), table_name='projectreport')
    op.drop_index(op.f('ix_projectreport_id'), table_name='projectreport')
    op.drop_table('projectreport')
    op.drop_index(op.f('ix_projectmilestone_project_id'), table_name='projectmilestone')
    op.drop_index(op.f('ix_projectmilestone_id'), table_name='projectmilestone')
    op.drop_table('projectmilestone')
    op.drop_index(op.f('ix_projectmember_user_id'), table_name='projectmember')
    op.drop_index(op.f('ix_projectmember_role_id'), table_name='projectmember')
    op.drop_index(op.f('ix_projectmember_project_id'), table_name='projectmember')
    op.drop_index(op.f('ix_projectmember_id'), table_name='projectmember')
    op.drop_table('projectmember')
    op.drop_index(op.f('ix_planpackageusagecount_project_id'), table_name='planpackageusagecount')
    op.drop_index(op.f('ix_planpackageusagecount_id'), table_name='planpackageusagecount')
    op.drop_table('planpackageusagecount')
    op.drop_index(op.f('ix_invoice_project_id'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_plan_id'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_invoice_id'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_id'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_rolepermission_role_id'), table_name='rolepermission')
    op.drop_index(op.f('ix_rolepermission_permission_id'), table_name='rolepermission')
    op.drop_index(op.f('ix_rolepermission_id'), table_name='rolepermission')
    op.drop_table('rolepermission')
    op.drop_index(op.f('ix_package_plan_id'), table_name='package')
    op.drop_index(op.f('ix_package_id'), table_name='package')
    op.drop_table('package')
    op.drop_index(op.f('ix_buildingproject_plan_id'), table_name='buildingproject')
    op.drop_index(op.f('ix_buildingproject_owner_id'), table_name='buildingproject')
    op.drop_index(op.f('ix_buildingproject_id'), table_name='buildingproject')
    op.drop_table('buildingproject')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_plan_id'), table_name='plan')
    op.drop_table('plan')
    op.drop_index(op.f('ix_permission_id'), table_name='permission')
    op.drop_table('permission')
    op.drop_index(op.f('ix_emailverificationcodes_otp_code'), table_name='emailverificationcodes')
    op.drop_index(op.f('ix_emailverificationcodes_id'), table_name='emailverificationcodes')
    op.drop_index(op.f('ix_emailverificationcodes_email'), table_name='emailverificationcodes')
    op.drop_table('emailverificationcodes')
    # ### end Alembic commands ###
