"""added null to reference and provider reference

Revision ID: 39a3afaba030
Revises: 112d8385b903
Create Date: 2026-02-02 12:35:47.861170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39a3afaba030'
down_revision: Union[str, Sequence[str], None] = '112d8385b903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'reference',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('transaction', 'provider_reference',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=400),
               nullable=True)
    op.create_index(op.f('ix_transaction_provider_reference'), 'transaction', ['provider_reference'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_provider_reference'), table_name='transaction')
    op.alter_column('transaction', 'provider_reference',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('transaction', 'reference',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
