"""add_authorization_url

Revision ID: 60dd516504d3
Revises: 8a85fd3729d2
Create Date: 2026-02-02 14:13:07.026908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60dd516504d3'
down_revision: Union[str, Sequence[str], None] = '8a85fd3729d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('authorization_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'authorization_url')
    # ### end Alembic commands ###
