"""added report package

Revision ID: 84d18855e578
Revises: bb24dd633dbf
Create Date: 2026-02-02 19:02:17.911278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d18855e578'
down_revision: Union[str, Sequence[str], None] = 'bb24dd633dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planpackageusagecount', sa.Column('package_tag', sa.String(length=50), nullable=False))
    op.drop_index(op.f('ix_planpackageusagecount_package_id'), table_name='planpackageusagecount')
    op.drop_constraint(op.f('planpackageusagecount_package_id_fkey'), 'planpackageusagecount', type_='foreignkey')
    op.drop_column('planpackageusagecount', 'package_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planpackageusagecount', sa.Column('package_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('planpackageusagecount_package_id_fkey'), 'planpackageusagecount', 'package', ['package_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_planpackageusagecount_package_id'), 'planpackageusagecount', ['package_id'], unique=False)
    op.drop_column('planpackageusagecount', 'package_tag')
    # ### end Alembic commands ###
