"""added relations

Revision ID: e0df2b0434e5
Revises: 84d18855e578
Create Date: 2026-02-07 17:21:57.068882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0df2b0434e5'
down_revision: Union[str, Sequence[str], None] = '84d18855e578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildingproject', sa.Column('subscription_end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildingproject', 'subscription_end_date')
    # ### end Alembic commands ###
