"""added number of floor

Revision ID: 5f685c286990
Revises: 1e184125edbf
Create Date: 2026-02-19 08:21:13.492413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f685c286990'
down_revision: Union[str, Sequence[str], None] = '1e184125edbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildingproject', sa.Column('floor_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildingproject', 'floor_number')
    # ### end Alembic commands ###
