"""added relations

Revision ID: 7ff06859e898
Revises: 96ad772291ab
Create Date: 2026-03-25 14:22:26.876448

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7ff06859e898"
down_revision: Union[str, Sequence[str], None] = "96ad772291ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projectmember",
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "projectmember",
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "projectmember", sa.Column("visit_type", sa.String(length=225), nullable=True)
    )
    op.add_column("projectmember", sa.Column("note", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projectmember", "note")
    op.drop_column("projectmember", "visit_type")
    op.drop_column("projectmember", "end_date")
    op.drop_column("projectmember", "start_date")
    # ### end Alembic commands ###
