"""make phone number has null

Revision ID: 8e49a25130e4
Revises: e97495f0a24f
Create Date: 2026-03-19 15:45:01.167796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e49a25130e4'
down_revision: Union[str, Sequence[str], None] = 'e97495f0a24f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.drop_constraint(op.f('user_phone_number_key'), 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_phone_number_key'), 'user', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('user', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    # ### end Alembic commands ###
