"""remove role_id

Revision ID: ca01d8350a2d
Revises: dd35d009acff
Create Date: 2026-03-25 17:45:03.996209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca01d8350a2d'
down_revision: Union[str, Sequence[str], None] = 'dd35d009acff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projectmember_role_id'), table_name='projectmember')
    op.drop_constraint(op.f('projectmember_role_id_fkey'), 'projectmember', type_='foreignkey')
    op.drop_column('projectmember', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projectmember', sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('projectmember_role_id_fkey'), 'projectmember', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_projectmember_role_id'), 'projectmember', ['role_id'], unique=False)
    # ### end Alembic commands ###
