"""update planpackage usage

Revision ID: e97495f0a24f
Revises: 5f685c286990
Create Date: 2026-02-19 12:03:55.511607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e97495f0a24f'
down_revision: Union[str, Sequence[str], None] = '5f685c286990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planpackageusagecount', sa.Column('payment_history', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_planpackageusagecount_payment_history'), 'planpackageusagecount', ['payment_history'], unique=False)
    op.create_foreign_key(None, 'planpackageusagecount', 'paymenthistory', ['payment_history'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planpackageusagecount', type_='foreignkey')
    op.drop_index(op.f('ix_planpackageusagecount_payment_history'), table_name='planpackageusagecount')
    op.drop_column('planpackageusagecount', 'payment_history')
    # ### end Alembic commands ###
